### ISSUE TITLE
Test script needs refactoring

### ISSUE THREAD

**Issue by bjpop** [bionitio-team/bionitio-test#1]
The test script needs refactoring:
- it has lots of unnecessary repetition
- when a test fails it tells us what the expected output was, but it does not tell us what the actual output was, which makes it hard to debug failed tests
- we do not currently test that the programs produce the correct header in the output

**Comment by multimeric** [comment]
Could they be refactored into python test cases? We can install whatever runtimes we need for testing on Travis, I would think

**Comment by bjpop** [comment]
That would be fine if we were only using it for Travis. However, I would like the test script to be able to run locally as well. At the moment it doesn't quite do that because it uses a non-portable call to `readlink -f`.

To remain portable, I think it would be better to stick with BASH, even though programming in BASH is a pain.

**Comment by bjpop** [comment]
This has been done
